// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesIgnis.Models;

namespace RazorPagesIgnis.Migrations
{
    [DbContext(typeof(RazorPagesIgnisContext))]
    partial class RazorPagesIgnisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("RazorPagesIgnis.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Mail");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("RazorPagesIgnis.Models.Feedback", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<bool>("Positive");

                    b.HasKey("ID");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("RazorPagesIgnis.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Client");

                    b.Property<string>("Description");

                    b.Property<string>("Level");

                    b.Property<string>("Specialty");

                    b.HasKey("ID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("RazorPagesIgnis.Models.ProjectAssigned", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Client");

                    b.Property<string>("Description");

                    b.Property<string>("Level");

                    b.Property<string>("Specialty");

                    b.Property<int?>("TechnicianID");

                    b.HasKey("ID");

                    b.HasIndex("TechnicianID");

                    b.ToTable("ProjectAssigned");
                });

            modelBuilder.Entity("RazorPagesIgnis.Models.ProjectFinished", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Client");

                    b.Property<string>("Description");

                    b.Property<int?>("FeedbackID");

                    b.Property<string>("Level");

                    b.Property<string>("Specialty");

                    b.Property<int?>("TechnicianID");

                    b.HasKey("ID");

                    b.HasIndex("FeedbackID");

                    b.HasIndex("TechnicianID");

                    b.ToTable("ProjectFinished");
                });

            modelBuilder.Entity("RazorPagesIgnis.Models.Technician", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Level");

                    b.Property<string>("Mail");

                    b.Property<string>("Name");

                    b.Property<string>("Specialty");

                    b.HasKey("ID");

                    b.ToTable("Technician");
                });

            modelBuilder.Entity("RazorPagesIgnis.Models.ProjectAssigned", b =>
                {
                    b.HasOne("RazorPagesIgnis.Models.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianID");
                });

            modelBuilder.Entity("RazorPagesIgnis.Models.ProjectFinished", b =>
                {
                    b.HasOne("RazorPagesIgnis.Models.Feedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FeedbackID");

                    b.HasOne("RazorPagesIgnis.Models.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianID");
                });
#pragma warning restore 612, 618
        }
    }
}
